helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.16.1
  releaseName: cert-manager
  namespace: cert-manager
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx
  namespace: ingress-nginx